apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: build-init
initializers:
  # the name needs to be fully qualified, i.e., containing at least two "."
  - name: experimental.mattmoor.io
    rules:
      # apiGroups, apiVersion, resources all support wildcard "*".
      # "*" cannot be mixed with non-wildcard.
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          # TODO(mattmoor): See this issue
          # https://github.com/kubernetes/kubernetes/issues/48388
          #  - jobs
          - replicasets
          # - statefulsets
          # - daemonsets
